In [41]:
import numpy as np
import pandas as pd

In [43]:
df1 = pd.read_csv('Seat_Matrix_Female_Only.csv')

In [45]:
df1

,Institute Name,Program Name,State/All India Seats,Seat Pool,OPEN,OPEN-PwD,GEN-EWS,GEN-EWS-PwD,SC,SC-PwD,ST,ST-PwD,OBC-NCL,OBC-NCL-PwD,Total (includes Female Supernumerary)
0,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",All India,Female-only (including Supernumerary),7,1,2,0,3,0,2,0,5,1,"21 (including ""0"" Supernumerary)"
1,Indian Institute of Technology Bhubaneswar,"Computer Science and Engineering (4 Years, Bac...",All India,Female-only (including Supernumerary),6,1,2,0,2,0,1,0,4,0,"16 (including ""0"" Supernumerary)"
2,Indian Institute of Technology Bhubaneswar,"Electrical Engineering (4 Years, Bachelor of T...",All India,Female-only (including Supernumerary),5,1,2,0,1,0,1,0,4,1,"15 (including ""0"" Supernumerary)"
3,Indian Institute of Technology Bhubaneswar,Electronics and Communication Engineering (4 Y...,All India,Female-only (including Supernumerary),4,0,1,0,1,0,1,0,3,1,"11 (including ""0"" Supernumerary)"
4,Indian Institute of Technology Bhubaneswar,"Engineering Physics (4 Years, Bachelor of Tech...",All India,Female-only (including Supernumerary),2,0,0,0,1,0,0,0,0,1,"4 (including ""0"" Supernumerary)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1344,Shri G. S. Institute of Technology and Science...,Electronics and Instrumentation Engineering (4...,All India,Female-only (including Supernumerary),0,0,0,0,0,0,0,0,0,0,"0 (including ""0"" Supernumerary)"
1345,Shri G. S. Institute of Technology and Science...,"Information Technology (4 Years, Bachelor of T...",All India,Female-only (including Supernumerary),0,0,0,0,0,0,0,0,0,0,"0 (including ""0"" Supernumerary)"
1346,Shri G. S. Institute of Technology and Science...,Industrial and Production Engineering (4 Years...,All India,Female-only (including Supernumerary),0,0,0,0,0,0,0,0,0,0,"0 (including ""0"" Supernumerary)"
1347,Shri G. S. Institute of Technology and Science...,Electronics and Telecommunication Engineering ...,All India,Female-only (including Supernumerary),0,0,0,0,0,0,0,0,0,0,"0 (including ""0"" Supernumerary)"
1348,Shri G. S. Institute of Technology and Science...,"Biomedical Engineering (4 Years, Bachelor of T...",All India,Female-only (including Supernumerary),0,0,0,0,0,0,0,0,0,0,"0 (including ""0"" Supernumerary)"

In [47]:
len(df1)

1349

In [49]:
df2 = pd.read_csv('Seat_Matrix_Gender_Neutral.csv')

In [51]:
df2

,Institute Name,Program Name,State/All India Seats,Seat Pool,OPEN,OPEN-PwD,GEN-EWS,GEN-EWS-PwD,SC,SC-PwD,ST,ST-PwD,OBC-NCL,OBC-NCL-PwD,Total (includes Female Supernumerary),Seat Capacity,Female Supernumerary
0,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",All India,Gender-Neutral,33,2,8,1,12,1,5,0,21,1,84,105,0
1,Indian Institute of Technology Bhubaneswar,"Computer Science and Engineering (4 Years, Bac...",All India,Gender-Neutral,27,0,6,0,9,1,4,1,17,1,66,82,0
2,Indian Institute of Technology Bhubaneswar,"Electrical Engineering (4 Years, Bachelor of T...",All India,Gender-Neutral,24,0,6,0,9,1,5,0,15,0,60,75,0
3,Indian Institute of Technology Bhubaneswar,Electronics and Communication Engineering (4 Y...,All India,Gender-Neutral,17,1,4,0,7,0,3,0,11,0,43,54,0
4,Indian Institute of Technology Bhubaneswar,"Engineering Physics (4 Years, Bachelor of Tech...",All India,Gender-Neutral,6,0,2,0,2,0,1,0,5,0,16,20,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1344,Shri G. S. Institute of Technology and Science...,Electronics and Instrumentation Engineering (4...,All India,Gender-Neutral,5,0,0,0,0,0,0,0,0,0,5,5,0
1345,Shri G. S. Institute of Technology and Science...,"Information Technology (4 Years, Bachelor of T...",All India,Gender-Neutral,6,0,0,0,0,0,0,0,0,0,6,6,0
1346,Shri G. S. Institute of Technology and Science...,Industrial and Production Engineering (4 Years...,All India,Gender-Neutral,4,0,0,0,0,0,0,0,0,0,4,4,0
1347,Shri G. S. Institute of Technology and Science...,Electronics and Telecommunication Engineering ...,All India,Gender-Neutral,5,0,0,0,0,0,0,0,0,0,5,5,0
1348,Shri G. S. Institute of Technology and Science...,"Biomedical Engineering (4 Years, Bachelor of T...",All India,Gender-Neutral,3,0,0,0,0,0,0,0,0,0,3,3,0

In [53]:
len(df2)

1349

In [55]:
import pandas as pd

# Get common columns
common_cols = df1.columns

# Extract only the common columns from df1
df2_common = df2[common_cols]

# Create a new DataFrame by interleaving rows
interleaved_rows = []
for i in range(len(df2)):
    interleaved_rows.append(df2_common.iloc[i])
    interleaved_rows.append(df1.iloc[i])

# Convert to DataFrame
merged_df = pd.DataFrame(interleaved_rows)

# Optionally reset index
merged_df.reset_index(drop=True, inplace=True)

In [57]:
merged_df

,Institute Name,Program Name,State/All India Seats,Seat Pool,OPEN,OPEN-PwD,GEN-EWS,GEN-EWS-PwD,SC,SC-PwD,ST,ST-PwD,OBC-NCL,OBC-NCL-PwD,Total (includes Female Supernumerary)
0,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",All India,Gender-Neutral,33,2,8,1,12,1,5,0,21,1,84
1,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",All India,Female-only (including Supernumerary),7,1,2,0,3,0,2,0,5,1,"21 (including ""0"" Supernumerary)"
2,Indian Institute of Technology Bhubaneswar,"Computer Science and Engineering (4 Years, Bac...",All India,Gender-Neutral,27,0,6,0,9,1,4,1,17,1,66
3,Indian Institute of Technology Bhubaneswar,"Computer Science and Engineering (4 Years, Bac...",All India,Female-only (including Supernumerary),6,1,2,0,2,0,1,0,4,0,"16 (including ""0"" Supernumerary)"
4,Indian Institute of Technology Bhubaneswar,"Electrical Engineering (4 Years, Bachelor of T...",All India,Gender-Neutral,24,0,6,0,9,1,5,0,15,0,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2693,Shri G. S. Institute of Technology and Science...,Industrial and Production Engineering (4 Years...,All India,Female-only (including Supernumerary),0,0,0,0,0,0,0,0,0,0,"0 (including ""0"" Supernumerary)"
2694,Shri G. S. Institute of Technology and Science...,Electronics and Telecommunication Engineering ...,All India,Gender-Neutral,5,0,0,0,0,0,0,0,0,0,5
2695,Shri G. S. Institute of Technology and Science...,Electronics and Telecommunication Engineering ...,All India,Female-only (including Supernumerary),0,0,0,0,0,0,0,0,0,0,"0 (including ""0"" Supernumerary)"
2696,Shri G. S. Institute of Technology and Science...,"Biomedical Engineering (4 Years, Bachelor of T...",All India,Gender-Neutral,3,0,0,0,0,0,0,0,0,0,3
2697,Shri G. S. Institute of Technology and Science...,"Biomedical Engineering (4 Years, Bachelor of T...",All India,Female-only (including Supernumerary),0,0,0,0,0,0,0,0,0,0,"0 (including ""0"" Supernumerary)"

In [59]:
len(merged_df)

2698

In [61]:
merged_df.to_csv("Merged_Seat_Matrix.csv" , index = False)